# Generated by Django 3.1.1 on 2020-09-25 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='view_count',
        ),
    ]
